name: Release a pre-release version

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Newest PDF
        run: wget "https://github.com/DanilJeston/DDLC-Chinese-Modding-Guide/raw/master/Main.pdf" -O "Main.pdf"
      - name: Delete old release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release delete night-build
      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            Main.pdf
          body_path: CHANGELOG-PRERELEASE.md
          tag_name: night-build
          prerelease: true
